2019-11-06 07:16:53,957 ERROR: Exception on /login [GET] [in /home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/donjoe/Desktop/projects/sched - 01/app/routes.py", line 87, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/donjoe/Desktop/projects/sched - 01/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/donjoe/Desktop/projects/sched - 01/app/templates/base.html", line 21, in top-level template code
    {% block content %} {% endblock %}
  File "/home/donjoe/Desktop/projects/sched - 01/app/templates/login.html", line 11, in block "content"
    {{ form.username.label }} <br>
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/wtforms/fields/core.py", line 393, in __html__
    return self()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/wtforms/fields/core.py", line 402, in __call__
    return widgets.HTMLString('<label %s>%s</label>' % (attributes, text or self.text))
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask_babel/speaklater.py", line 23, in __str__
    return text_type(self._func(*self._args, **self._kwargs))
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask_babel/__init__.py", line 552, in gettext
    t = get_translations()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask_babel/__init__.py", line 227, in get_translations
    [get_locale()],
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask_babel/__init__.py", line 257, in get_locale
    rv = babel.locale_selector_func()
  File "/home/donjoe/Desktop/projects/sched - 01/app/__init__.py", line 41, in get_locale
    return request.accept_languages.best_match(app.config['LANGUAGE'])
KeyError: 'LANGUAGE'
2019-11-06 07:18:43,268 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched - 01/app/__init__.py:36]
2019-11-06 10:00:06,963 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched - 01/app/__init__.py:49]
2019-11-06 10:31:12,844 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched - 01/app/__init__.py:49]
2019-11-06 10:31:19,004 ERROR: Exception on /login [GET] [in /home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/werkzeug/routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1815, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1743, in handle_http_exception
    return handler(e)
  File "/home/donjoe/Desktop/projects/sched - 01/app/errors/handlers.py", line 8, in not_found_error
    return render_template('404.html'), 404
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: 404.html
