2019-11-05 18:40:12,855 ERROR: Exception on /explore [GET] [in /home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/donjoe/Desktop/projects/sched/app/routes.py", line 166, in explore
    return render_template('index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/donjoe/Desktop/projects/sched/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/donjoe/Desktop/projects/sched/app/templates/base.html", line 21, in top-level template code
    {% block content %} {% endblock %}
  File "/home/donjoe/Desktop/projects/sched/app/templates/index.html", line 20, in block "content"
    <ul class="list-group"><li class="list-group-item">{% include 'includes/_post.html' %}</li>
  File "/home/donjoe/Desktop/projects/sched/app/templates/includes/_post.html", line 10, in top-level template code
    {{ _l('%(username)s said %(when)s', username=user_link, when=moment(post.timestamp).fromNow()) }}
jinja2.exceptions.UndefinedError: '_l' is undefined
2019-11-05 18:40:14,983 ERROR: Exception on /explore [GET] [in /home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/donjoe/Desktop/projects/sched/app/routes.py", line 166, in explore
    return render_template('index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/donjoe/Desktop/projects/sched/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/donjoe/Desktop/projects/sched/app/templates/base.html", line 21, in top-level template code
    {% block content %} {% endblock %}
  File "/home/donjoe/Desktop/projects/sched/app/templates/index.html", line 20, in block "content"
    <ul class="list-group"><li class="list-group-item">{% include 'includes/_post.html' %}</li>
  File "/home/donjoe/Desktop/projects/sched/app/templates/includes/_post.html", line 10, in top-level template code
    {{ _l('%(username)s said %(when)s', username=user_link, when=moment(post.timestamp).fromNow()) }}
jinja2.exceptions.UndefinedError: '_l' is undefined
2019-11-05 18:41:05,994 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched/app/__init__.py:36]
2019-11-05 18:45:38,010 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched/app/__init__.py:36]
2019-11-05 18:47:45,474 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched/app/__init__.py:36]
2019-11-05 18:51:47,174 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched/app/__init__.py:36]
2019-11-05 19:02:28,657 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched/app/__init__.py:36]
2019-11-06 07:16:45,281 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched - 01/app/__init__.py:36]
