2019-11-25 22:17:58,156 ERROR: Exception on /index [POST] [in /home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/donjoe/Desktop/projects/sched - 01/app/main/routes.py", line 39, in index
    db.session.commit()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 501, in commit
    self.session.dispatch.after_commit(self.session)
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/sqlalchemy/event/attr.py", line 261, in __call__
    fn(*args, **kw)
  File "/home/donjoe/Desktop/projects/sched - 01/app/models.py", line 120, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "/home/donjoe/Desktop/projects/sched - 01/app/search.py", line 5, in add_to_index
    if not current_app.elasticsearch:
  File "/home/donjoe/Desktop/projects/sched/venv/lib/python3.5/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'elasticsearch'
2019-11-25 22:22:00,347 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched - 01/app/__init__.py:71]
2019-11-27 03:46:10,935 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched_blog/app/__init__.py:71]
2019-11-27 09:55:08,088 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched_blog/app/__init__.py:71]
2019-11-27 09:55:08,088 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched_blog/app/__init__.py:89]
2019-11-27 09:55:08,088 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched_blog/app/__init__.py:89]
2019-11-27 09:55:16,004 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched_blog/app/__init__.py:71]
2019-11-27 09:55:16,005 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched_blog/app/__init__.py:89]
2019-11-27 09:55:16,005 INFO: Microblog startup [in /home/donjoe/Desktop/projects/sched_blog/app/__init__.py:89]
